### ISSUE TITLE
NULL pointer to instance

### ISSUE THREAD

**Issue by BorizzK** [ralian/eai#14]
https://github.com/ralian/eai/blob/0fd4220ce8536158bd4602b9f8fcb6eb926db732/Scripts/4_World/eAI/Entities/AI/eAIBase.c#L240

**Comment by BorizzK** [comment]
Function: 'EEHitBy'
Stack trace:
eAI/Scripts/4_World/eai\entities\ai\eaibase.c:240
SCRIPT    (E): NULL pointer to instance
Class:      'eAI_SurvivorM_Seth'
Entity id:2975470

may be change condition check to

		if (Class.CastTo(zmb, source))
		{
			if (!zmb.GetTargetInformation().IsTargetted(m_eAI_Group)) zmb.GetTargetInformation().AddAI(this);

		}

**Comment by ralian** [comment]
@BorizzK That wouldn't fix the issue since it's the same as the lazy evaluation above

the solution would likely be something like

`if (Class.CastTo(zmb, source) && zmb.GetTargetInformation() && !zmb.GetTargetInformation().IsTargetted(m_eAI_Group)) `

but I'm going to let Jacob weigh in since it's his code

**Comment by ralian** [comment]
Closing as this has been fixed by a reversion on main
